config/routes.rb
Rails.application.routes.draw do

  devise_for :users, skip: :registrations, controllers: {
    registrations: 'users/registrations'
  }

  as :user do
    get '/users' => 'users/registrations#index'
    get '/users/sign_up' => 'users/registrations#new', as: :new_user_registration
    get '/users/edit' => 'users/registrations#edit', as: :edit_user_registration
    post '/users' => 'users/registrations#create', as: :user_registration
    put '/users/edit/:id' => 'users/registrations#update', as: :update_user_registration
    patch '/users/:id' => 'users/registrations#update', as: :patch_user_registration
    delete '/users/:id' => 'users/registrations#destroy', as: :destroy_user_registration

    put '/users/password/:id' => 'users/registrations#update_password', as: :password
  end

  get 'drivers/reports' => 'drivers#reports'
  post 'drivers/state' => 'drivers#state_drivers', as: :state_drivers
  get 'drivers/state' => 'drivers#show_state_drivers', as: :show_state_drivers

  get 'reports/index' => 'reports#index'

  root 'drivers#index'
  resources :drivers

end

app/models/driver.rb
class Driver < ActiveRecord::Base
  geocoded_by :current_location
  after_validation :geocode

  belongs_to :user

  ransacker :full_name do |parent|
    Arel::Nodes::InfixOperation.new('||',
      Arel::Nodes::InfixOperation.new('||',
        parent.table[:first_name], Arel::Nodes.build_quoted(' ')
      ),
      parent.table[:last_name]
    )
  end

  def full_name
    "#{first_name} #{last_name}"
  end



  def current_location
    current_city_exists = current_city != nil && current_city.length != 0
    current_state_exists = current_state != nil && current_state.length != 0
    if current_city_exists && current_state_exists
      return "#{current_city}, #{current_state}"
    elsif current_city_exists
      return "#{current_city}"
    elsif current_state_exists
      return "#{current_state}"
    end
    ""
  end

  def desired_location
    desired_city_exists = desired_city != nil && desired_city.length != 0
    desired_state_exists = desired_state != nil && desired_state.length != 0
    if desired_city_exists && desired_state_exists
      return "#{desired_city}, #{desired_state}"
    elsif desired_city_exists
      return "#{desired_city}"
    elsif desired_state_exists
      return "#{desired_state}"
    end
    ""
  end

  def driver_info
    "#{desired_state} #{desired_zip} #{driver_phone}"
  end

  def gmaps4rails_marker_picture
   {
    "picture" => "/assets/images/map2s.png",          # string,  mandatory
     "width" =>  "32",          # integer, mandatory
     "height" => "32",          # integer, mandatory
                       # See doc here: http://google-maps-utility-library-v3.googlecode.com/svn/trunk/richmarker/docs/reference.html
   }
  end

  def self.search(search)
   where("first_name LIKE ? OR desired_state LIKE ?", "%#{search}%", "%#{search}%")
  end

  def self.desired_city(desired)
    desired = all
    desired = desired.where("desired_city LIKE ?", "%#{desired}%")
    return desired
  end

  validates :first_name, presence: true, allow_blank: false

end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  include ApplicationHelper

  before_action :authenticate_user!
  before_action :set_driver,  only: [:show, :edit, :update, :destroy ]

  # GET /drivers
  # GET /drivers.json
  def index
    if current_user.report
      current_user.report.delete
    end
    @q = Driver.ransack(params[:q])
    @drivers = @q.result(distinct: true).order(updated_at: :desc)
    covered_drivers = {}
    @drivers.joins(:user).each do | d |
      covered_drivers[d.id] = d.user.full_name
    end
    @located_drivers = get_located_drivers @drivers
    @hash = generate_hash_map @located_drivers
    respond_to do |format|
        format.html
        format.json {
          render json: {
            drivers: @drivers,
            covered_drivers: covered_drivers
          },
          status: :ok
        }
    end
  end

  # def home_feed
  #   @drivers = Driver.ransack(params[:q])
  #   render :partial => "/drivers"
  # end

  def state_drivers
    new_params = {
      :state_lat => params[:state_lat],
      :state_lng => params[:state_lng]
    }
    redirect_to show_state_drivers_path new_params
  end

  def show_state_drivers
    result = Geocoder.search([ params[:state_lat], params[:state_lng] ])
    if !result[0]
      @drivers = []
      @located_drivers = []
      @hash = generate_hash_map []
      @state = 'Unknown Region'
      return
    end
    @state = result[0].state
    @drivers = get_click_point_drivers @state
    @located_drivers = get_located_drivers @drivers
    @hash = generate_hash_map @located_drivers
  end

  def get_click_point_drivers state
    Driver.select do |d|
      d.current_state == state
    end
  end

  def get_located_drivers drivers
    drivers.select do |driver|
      driver.latitude && driver.longitude
    end
  end

  def generate_hash_map located_drivers
    Gmaps4rails.build_markers(located_drivers) do |driver, marker|
      driver_path = view_context.link_to driver.full_name, driver_path(driver)
      driver_id_tag = driver.driver_id_tag
      driver_desired = driver.desired_state
      driver_phone = driver[:driver_phone]
      truck_type = driver[:driver_truck_type]
      available = driver.driver_availability.strftime("%m/%d/%Y")
      comments = driver[:comments]
      marker.lat driver.latitude
      marker.lng driver.longitude
      marker.title driver.full_name
      marker.json(:id => driver[:id])
      marker.infowindow (
        %Q(
          Driver: #{driver_path}<br><br>
          Driver ID: #{driver_id_tag}<br><br>
          Phone: #{driver_phone}<br><br>
          Desired State: #{driver_desired}<br><br>
          Truck Type: #{truck_type}<br><br>
          Available Date: #{available}<br><br>
          Comments: #{comments}
        )
      )
      if driver.active == true
        marker.picture({
         :url => "http://chart.apis.google.com/chart?chst=d_map_pin_letter&chld=A|008000|000000",
         :width   => 32,
         :height  => 32
        })
        next
      end
      marker.picture({
       :url => "http://chart.apis.google.com/chart?chst=d_map_pin_letter&chld=N|ff0000|000000",
       :width   => 80,
       :height  => 80
      })
    end
  end

  # GET /drivers/1
  # GET /drivers/1.json
  def show
    report = current_user.report
    @report_ids = report && report[:driver_ids].length != 0 ?
      report[:driver_ids] :
      []

    if @report_ids.length != 0
      miles = report[:miles]
      @next_idx = get_next_report_idx(@report_ids, @driver.id)
      @previous_idx = get_previous_report_idx(@report_ids, @driver.id)
      search_params = {}
      report.attributes.each_pair do | k, v |
        if k != 'id' && k != 'driver_ids' && k != 'miles' && k != 'created_at' && k != 'updated_at'
          search_params[k] = v
        end
      end
      @search_params = { :q => search_params, :miles => miles }
    end
  end

  def get_next_report_idx report, id
    last_index = report.length - 1
    report.index(id) + 1 <= last_index ?
      report.index(id) + 1 : 0
  end

   def get_previous_report_idx report, id
    last_index = report.length - 1
    report.index(id) - 1 < 0 ?
      last_index : report.index(id) - 1
  end

  # GET /drivers/new
  def new
    @driver = Driver.new
  end

  # GET /drivers/1/edit
  def edit
  end

  # POST /drivers
  # POST /drivers.json
  def create
    params[:driver][:first_name].strip!
    params[:driver][:last_name].strip!

    desired_state = params[:driver][:desired_state]
    desired_city = params[:driver][:desired_city]
    if desired_state && desired_state.length != 0
      state_abbrv = get_state_abbrev desired_state
      zone = get_destination_zone state_abbrv
      params[:driver][:destination_zone] = zone
    elsif desired_city && desired_city.length != 0
      result = Geocoder.search(desired_city)
      if result[0]
        state_abbrv = get_state_abbrev result[0].state
        zone = get_destination_zone state_abbrv
        params[:driver][:desired_state] = result[0].state
        params[:driver][:destination_zone] = zone
      end
    else
      params[:driver][:destination_zone] = nil
    end

    current_state = params[:driver][:current_state]
    current_city = params[:driver][:current_city]
    if current_state && current_state.length != 0
      params[:driver][:backhaul] = current_state == 'California' ? false : true
    elsif current_city && current_city.length != 0
      loc = Geocoder.search(current_city, :params => {:countrycodes => 'us'})
      if loc.length != 0
        params[:driver][:backhaul] = loc[0].state == 'California' ? false : true
      end
    elsif current_state.length == 0 && current_city.length == 0
      params[:driver][:backhaul] = true
    end

     if current_state && current_state.length != 0
      state_abbrv = get_state_abbrev current_state
      current_zone = get_current_zone state_abbrv
      params[:driver][:current_zone] = current_zone
    elsif current_city && current_city.length != 0
      result = Geocoder.search(current_city)
      if result[0]
        state_abbrv = get_state_abbrev result[0].state
        zone = get_current_zone state_abbrv
        params[:driver][:current_state] = result[0].state
        params[:driver][:current_zone] = zone
      end
    else
      params[:driver][:current_zone] = nil
    end

    params[:driver][:last_updated_by] = current_user.full_name
    @driver = Driver.new(driver_params)

    respond_to do |format|
      if @driver.save
        format.html { redirect_to @driver, notice: 'Driver was successfully created.' }
        format.json { render :show, status: :created, location: @driver }
      else
        format.html { render :new }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drivers/1
  # PATCH/PUT /drivers/1.json
  def update
    params[:driver][:first_name].strip!
    params[:driver][:last_name].strip!

    covered_name = nil
    if params[:driver][:Covered] == '1'
      params[:driver][:user_id] = current_user.id
      covered_name = current_user.full_name
    else
      params[:driver][:user_id] = nil
    end

    desired_state = params[:driver][:desired_state]
    desired_city = params[:driver][:desired_city]
    if desired_state && desired_state.length != 0
      state_abbrv = get_state_abbrev desired_state
      zone = get_destination_zone state_abbrv
      params[:driver][:destination_zone] = zone
    elsif desired_city && desired_city.length != 0
      result = Geocoder.search(desired_city)
      if result[0]
        state_abbrv = get_state_abbrev result[0].state
        zone = get_destination_zone state_abbrv
        params[:driver][:desired_state] = result[0].state
        params[:driver][:destination_zone] = zone
      end
    else
      params[:driver][:destination_zone] = nil
    end

    current_state = params[:driver][:current_state]
    current_city = params[:driver][:current_city]
    if current_state && current_state.length != 0
      params[:driver][:backhaul] = current_state == 'California' ? false : true
    elsif current_city && current_city.length != 0
      loc = Geocoder.search(current_city, :params => {:countrycodes => 'us'})
      if loc.length != 0
        params[:driver][:backhaul] = loc[0].state == 'California' ? false : true
      end
    elsif current_state.length == 0 && current_city.length == 0
      params[:driver][:backhaul] = true
    end

    if current_state && current_state.length != 0
      state_abbrv = get_state_abbrev current_state
      current_zone = get_current_zone state_abbrv
      params[:driver][:current_zone] = current_zone
    elsif current_city && current_city.length != 0
      result = Geocoder.search(current_city)
      if result[0]
        state_abbrv = get_state_abbrev result[0].state
        zone = get_current_zone state_abbrv
        params[:driver][:current_state] = result[0].state
        params[:driver][:current_zone] = zone
      end
    else
      params[:driver][:current_zone] = nil
    end

    params[:driver][:last_updated_by] = current_user.full_name
    respond_to do |format|
      if @driver.update(driver_params)
        format.html { redirect_to @driver, notice: 'Driver was successfully updated.' }
        format.json { render :show, status: :ok, location: @driver }
      else
        format.html { render :edit }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drivers/1
  # DELETE /drivers/1.json
  def destroy
    @driver.destroy
    respond_to do |format|
      format.html { redirect_to drivers_url, notice: 'Driver was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  # search
  def reports
    radius = params[:miles] && params[:miles].length != 0
    start_date = nil
    end_date = nil
    address = nil
    lat_lon = nil
    radius_drivers = nil
    range_drivers = nil
    saved_range = nil
    saved_state = nil
    saved_city = nil

app/helpers/drivers_helper.rb
module DriversHelper
end

app/views/drivers/edit.html.erb
<div class="container driver-container">
  <div>
    <div>
      <div class="page-header">
        <h1>Editing Driver</h1>
      </div>
    </div>
  </div>
  <%= render :partial => 'form', :locals => {:editing => true} %>
  <% search_hash = {} %>
  <%
    if params[:search]
      params[:search].each do |sp|
        search_hash[sp] = params[:search][sp]
      end
    end
  %>
  <%= link_to 'Cancel',
    driver_path(
      id: @driver.id,
      search: search_hash,
      report: params[:report]
    ), class: 'btn btn-danger link-btn' %>
</div>

app/views/drivers/index.html.erb
<% if user_signed_in? %>
  <% account_type = current_user.account_type %>

  <div id='map-container' style='width: 100%;'>
    <div id="map" style='width: 100%; height: 800px;'></div>
    <div id='legend'>
      <h4> Map Legend </h4>
      <div class='legend-image'>
        <img src='http://chart.apis.google.com/chart?chst=d_map_pin_letter&chld=A|008000|000000' />  Driver available
      </div>
      <div class='legend-image'>
        <img src='http://chart.apis.google.com/chart?chst=d_map_pin_letter&chld=N|ff0000|000000' /> Driver not available
      </div>
    </div>
  </div>


  <script type="text/javascript">
    $( document ).ready(function() {
      handler = Gmaps.build(
        'Google',
        {
          markers: {
            maxRandomDistance: 100,
            clusterer: { maxZoom: 12, gridSize: 40 }
          }
        }
      );
      Gmaps.store = {};
      handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
        var rawData = <%= raw @hash.to_json %>
        try {
          Gmaps.store.markers = rawData.map(function(m){
            var marker = handler.addMarker(m);
            marker.serviceObject.set('id', m.id);
            return marker;
          });
          handler.bounds.extendWith(Gmaps.store.markers);
          handler.fitMapToBounds();
        } catch (e) {
          // Gmaps sometimes kicks an error for no apparent reason
          // Cannot read property 'addMarker' of undefined
          // Since markers always seem to work fine despite this error,
          // we're ignoring this for now so it's doesn't print to the console
        }
      });

      var infoWindow = new handler.builders.Map.PRIMITIVES.infowindow();
      var map = handler.getMap();

      var stateReportButton = "<a id='state-report-link'> Generate State Report </a>";
      var isOpen = false;

      function sendData(latLng, evt) {
        evt.preventDefault();
        $.ajax({
          method: 'POST',
          url: "<%= state_drivers_path %>",
          data: latLng
        });
      }

      map.addListener('click', function(evt) {
        if (isOpen) {
          $('#state-report-link').off('click', sendData);
          infoWindow.close();
          isOpen = false;
        }
      });
      map.addListener('rightclick', function(evt) {
        if (isOpen) {
          $('#state-report-link').off('click', sendData);
          infoWindow.close();
          isOpen = false;
        }
        var position = evt.latLng;
        var clickedPoint = {};
        clickedPoint.state_lat = position.lat();
        clickedPoint.state_lng = position.lng();
        infoWindow.setContent(stateReportButton);
        infoWindow.setPosition(position);
        infoWindow.open(map, this);
        isOpen = true
        $('#state-report-link').on('click', sendData.bind(this, clickedPoint));
      });

      function handleHtmlData(html) {
        var $div = $('<div>');
        $div.html(html);
        var $content = $div.find('#driver-feed');
        $feed.html($content.html());
      }

      var $feed = $('#driver-feed');
      $('#feed-name-filter').on('keydown', function(evt) {
        setTimeout(function() {
          var $form = $('#driver-feed-form');
          var formData = $form.serialize();
          $.get('drivers', formData, handleHtmlData);
        }, 0);
      });

      $('#feed-phone-filter').on('keydown', function(evt) {
        setTimeout(function() {
          var $form = $('#driver-feed-form');
          var formData = $form.serialize();
          $.get('drivers', formData, handleHtmlData);
        }, 0);
      });

      $('#feed-id-filter').on('keydown', function(evt) {
        setTimeout(function() {
          var $form = $('#driver-feed-form');
          var formData = $form.serialize();
          $.get('drivers', formData, handleHtmlData);
        }, 0);
      });


    });
  </script>

  <div id='drivers-heading'>
    <h1>Driver Feed</h1>
    <%= search_form_for @q, id: 'driver-feed-form', url: drivers_path do |f| %>
      <div id="driver-feed-filter">
        <%= f.label :driver_name, "Driver Name", class: 'feed-label' %>
        <%= f.text_field :full_name_cont, class: 'feed-filter', id: 'feed-name-filter' %>
        <%= f.label :driver_phone, "Driver Phone",class: 'feed-label' %>
        <%= f.text_field :driver_phone_cont, class: 'feed-filter', id: 'feed-phone-filter'%>
        <%= f.label :driver_id_tag, "Driver ID",class: 'feed-label' %>
        <%= f.text_field :driver_id_tag_cont, class: 'feed-filter', id: 'feed-id-filter'%>
        <%= link_to 'Clear Form', drivers_path, :class => 'btn btn-success link-btn' %>
        <% if account_type != 'dispatcher' %>
          <%= link_to 'Create New Driver', new_driver_path, class: 'btn btn-primary link-btn' %>
        <% end %>
      </div>
    <% end %>
  </div>

 <div id ="feed"> <%= render :partial => 'feed', :locals => {:data_id => 'driver-feed'} %> </div>

<% else %>

  <div class="container main-pg">
    <div class="row">
      <div class="col-md-4"></div>
      <div class="col-md-4">
        <section class="login-form">
          <%= form_for(:user, :url => session_path(:user)) do |f| %>
            <%= f.text_field :email, placeholder: "E-Mail Address" %>
            <%= f.password_field :password, placeholder: "Password"  %> </br>
            <%= f.check_box :remember_me %>
            <%= f.label :remember_me %>
            <%= f.submit 'Sign in' , :class => "btn btn-md btn-primary btn-block"  %>
            <%= link_to "Forgot your password?", new_password_path(:user) %>
          <% end %>
        </section>
      </div>
    </div>
  </div>
<% end %>

app/views/drivers/reports.html.erb
<script type="text/javascript">
  $( document ).ready(function() {
    $("#q_driver_phone_eq").inputmask({"mask": "(999) 999-9999"});
    var q = <%= raw params[:q].to_json %>;
    var opts = {
      autoUpdateInput: false,
      locale: {
        cancelLabel: 'Clear'
      }
    };
    if (q && q.driver_availability_in.length) {
      var range = q.driver_availability_in.split(' - ');
      opts.startDate = range[0];
      opts.endDate = range[1];
      $('#datefilter').val(opts.startDate + ' - ' + opts.endDate);
    }
    $('#datefilter').daterangepicker(opts);

    $('#datefilter').on('apply.daterangepicker', function(ev, picker) {
      var startDate = picker.startDate.format('MM/DD/YYYY');
      var endDate = picker.endDate.format('MM/DD/YYYY');
      var value = (startDate + ' - ' + endDate);
      $(this).val(value);
    });

    $('#datefilter').on('cancel.daterangepicker', function(ev, picker) {
      $(this).val('');
    });
  });
</script>

<div id='advanced-reporting'>

  <h1> Reports </h1>

  <%= search_form_for @q, url: drivers_reports_path do |f| %>
    <div class="search-report-container form-group">

      <div class='search-report-top-section'>

        <div class='search-report-section col1'>
          <%= f.label :full_name_cont, "Driver Name", class: 'report-label' %>
          <%= f.text_field :full_name_cont%>
          <br />

          <%= f.label :driver_id_tag, "Driver ID",class: 'report-label' %>
          <%= f.text_field :driver_id_tag_eq%>
          <br>

          <%= f.label :current_state, class: 'report-label' %>
          <% state = params[:q] && params[:q][:current_state_eq] ?
            params[:q][:current_state_eq] : ''
          %>
          <%= f.select :current_state_eq,
            options_for_select(us_states, state),
            :include_blank => true %>
          <br />

          <%= f.label :current_city, class: 'report-label' %>
          <% city = params[:q] && params[:q][:current_city_cont] ?
            params[:q][:current_city_cont] : ''
          %>
          <%= f.text_field :current_city_cont, value: city %>
          <br />

          <%= f.label 'Radius (mi)', class: 'report-label' %>
          <%= number_field_tag :miles, params[:miles], min: 1 %>
          <br>

          <%= f.label :driver_company, "Company Name", class: 'report-label' %>
          <%= f.text_field :driver_company_cont%>
        </div>

        <div class='search-report-section col2'>
          <%= f.label :driver_phone, "Driver Phone",class: 'report-label' %>
          <%= f.telephone_field :driver_phone_cont %>
          <br />

          <%= f.label :driver_truck_type, "Trailer Type", class: 'report-label' %>
          <%= f.select(
            :driver_truck_type_eq,
            options_for_select(
              [
                ['53R', '53R'],
                ['53RM', '53RM'],
                ['53V', '53V'],
                ['53VM', '53VM'],
                ['flat', 'flat'],
                ['48R', '48R'],
                ['48V', '48V']
              ],
              params[:q] ? params[:q][:driver_truck_type_eq] : ''
            ),
            include_blank: true
          ) %>
          <br />

          <% if current_user.account_type != 'dispatcher' %>
            <%= f.label :active, class: 'report-label' %>
            <%= f.select(
              :active_eq,
              options_for_select(
                [
                  ['Answering', true], ['Not Answering', false]
                ],
                params[:q] ? params[:q][:active_eq] : ''
              ),
              include_blank: true
            ) %>
            <br>
          <% end %>

          <%= f.label :PlateTrailer, "Plate Trailer", class: 'report-label' %>
          <%= f.check_box :PlateTrailer_eq %>
          <span id='plate-trailer-warning'>
            ALWAYS CONFIRM W/ DRIVER
          </span>
          <br>

          <%= f.label :ETrac, "E-Trac",class: 'report-label' %>
          <%= f.check_box :Etrac_eq %>
          <br>

          <%= f.label :backhaul, class: 'report-label' %>
          <%= f.check_box :backhaul_eq %>
          <br>

          <%= f.label :driver_availability, class: 'report-label' %>
          <%= f.text_field :driver_availability_in, id: 'datefilter' %>
        </div>
      </div>

      <div class='search-report-bottom-section'>

        <div class='search-report-section col3'>
          <div class='report-label-top'>
            <%= f.label "Preferred Lanes" %>
          </div>
          <%= f.select(
            :PreferredLanes_cont_any,
            options_for_select(
              us_states,
              params[:q] ? params[:q][:PreferredLanes_cont_any] : ''
            ),
            { include_hidden: false },
            {
              class: 'form-control multi-select',
              multiple: true,
            }
          ) %>
        </div>

        <div class='search-report-section col4'>
          <div class='report-label-top'>
            <%= f.label :destination_zone, "Destination Zones" %>
          </div>
          <%= f.select(
            :destination_zone_cont_any,
            options_for_select(
              [
                ['Z0 [CT,ME,MA,NH,NJ,RI,VT]', 'Z0'],
                ['Z1 [DE,NY,PA]', 'Z1'],
                ['Z2 [DC,MD,NC,SC,VA,WV]', 'Z2'],
                ['Z3 [AL,FL,GA,MS,TN]', 'Z3'],
                ['Z4 [IN,KY,MI,OH]', 'Z4'],
                ['Z5 [IA,MN,MT,ND,SD,WI]', 'Z5'],
                ['Z6 [IL,KS,MO,NE]', 'Z6'],
                ['Z7 [AR,LA,OK,TX]', 'Z7'],
                ['Z8 [AZ,CO,ID,NV,NM,UT,WY]', 'Z8'],
                ['Z9 [CA,OR,WA]', 'Z9']
              ],
              params[:q] ? params[:q][:destination_zone_cont_any] : ''
            ),
            { include_hidden: false },
            {
              class: 'form-control multi-select',
              multiple: true,
            }
          ) %>
        </div><!--

     --><div class='search-report-section col5'>
          <div class='report-label-top'>
            <%= f.label :current_zone, "Current Zones" %>
          </div>
          <%= f.select(
            :current_zone_cont_any,
            options_for_select(
              [
                ['Z0 [CT,ME,MA,NH,NJ,RI,VT]', 'Z0'],
                ['Z1 [DE,NY,PA]', 'Z1'],
                ['Z2 [DC,MD,NC,SC,VA,WV]', 'Z2'],
                ['Z3 [AL,FL,GA,MS,TN]', 'Z3'],
                ['Z4 [IN,KY,MI,OH]', 'Z4'],
                ['Z5 [IA,MN,MT,ND,SD,WI]', 'Z5'],
                ['Z6 [IL,KS,MO,NE]', 'Z6'],
                ['Z7 [AR,LA,OK,TX]', 'Z7'],
                ['Z8 [AZ,CO,ID,NV,NM,UT,WY]', 'Z8'],
                ['Z9 [CA,OR,WA]', 'Z9']
              ],
              params[:q] ? params[:q][:current_zone_cont_any] : ''
            ),
            { include_hidden: false },
            {
              class: 'form-control multi-select',
              multiple: true,
            }
          ) %>
        </div>

      </div>

    </div>

    <div class='report-buttons'>
      <%= f.submit "Search", class: "btn btn-primary" %>
      <span><%= link_to 'Clear Form', drivers_reports_path, :class => 'btn btn-success' %></span>
    </div>
  <% end %>

  <%= render :partial => 'feed2', :locals => {:data_id => 'report-feed'} %>

</div>

app/views/drivers/show_state_drivers.html.erb
<% if user_signed_in? %>
  <% account_type = current_user.account_type %>

 <h1 style='text-align: center;'> State Report for <%= @state %> </h1>
  <div style='margin: 0 auto; width: fit-content;'>
    <div id="map" style='width: 800px; height: 400px;'></div>
  </div>

  <script type="text/javascript">
    var handler = Gmaps.build(
      'Google',
      {
        markers: {
          maxRandomDistance: 100,
          clusterer: { maxZoom: 12, gridSize: 40 }
        }
      }
    );
    handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
      var rawData = <%= raw @hash.to_json %>
      var lat = rawData[0] ? rawData[0].lat : '';
      var lng = rawData[0] ? rawData[0].lng : '';
      try {
        var markers = handler.addMarkers(rawData);
        if (lat && lng) {
          handler.map.centerOn({lat: lat, lng: lng});
          handler.getMap().setZoom(7);
        }
      } catch (e) {
        // Gmaps sometimes kicks an error for no apparent reason
        // Cannot read property 'addMarker' of undefined
        // Since markers always seem to work fine despite this error,
        // we're ignoring this for now so it's doesn't print to the console
      }
    });
  </script>

  <%= render :partial => 'feed3', :locals => {:data_id => 'state-report'} %>

<% else %>

  <div class="container main-pg">
    <div class="row">
      <div class="col-md-4"></div>
      <div class="col-md-4">
        <section class="login-form">
          <%= form_for(:user, :url => session_path(:user)) do |f| %>
            <%= f.text_field :email, placeholder: "E-Mail Address" %>
            <%= f.password_field :password, placeholder: "Password"  %> </br>
            <%= f.check_box :remember_me %>
            <%= f.label :remember_me %>
            <%= f.submit 'Sign in' , :class => "btn btn-md btn-primary btn-block"  %>
            <%= link_to "Forgot your password?", new_password_path(:user) %>
          <% end %>
        </section>
      </div>
    </div>
  </div>
<% end %>