config/routes.rb
Rails.application.routes.draw do

  devise_for :users, skip: :registrations, controllers: {
    registrations: 'users/registrations'
  }

  as :user do
    get '/users' => 'users/registrations#index'
    get '/users/sign_up' => 'users/registrations#new', as: :new_user_registration
    get '/users/edit' => 'users/registrations#edit', as: :edit_user_registration
    post '/users' => 'users/registrations#create', as: :user_registration
    put '/users/edit/:id' => 'users/registrations#update', as: :update_user_registration
    patch '/users/:id' => 'users/registrations#update', as: :patch_user_registration
    delete '/users/:id' => 'users/registrations#destroy', as: :destroy_user_registration

    put '/users/password/:id' => 'users/registrations#update_password', as: :password
  end

  get 'drivers/reports' => 'drivers#reports'
  post 'drivers/state' => 'drivers#state_drivers', as: :state_drivers
  get 'drivers/state' => 'drivers#show_state_drivers', as: :show_state_drivers

  get 'reports/index' => 'reports#index'

  root 'drivers#index'
  resources :drivers

end

app/models/report.rb
class Report < ApplicationRecord

  belongs_to :user

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/index.html.erb
<%= form_tag reports_index_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :first_name => nil %><br>

  </p>
<% end %>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Full Name</th>
      <th>Address</th>
      <th>Desired City</th>
      <th>Desired State</th>
      <th>Desired Zip</th>
      <th>Driver ID</th>
      <th>Phone</th>
      <th>Truck Type</th>
      <th>Active</th>
      <th>Driver status</th>
      <th>Contract Number</th>
      <th>Availability</th>
      <th>Company</th>
      <th>Comments</th>
      <th colspan="12"></th>
    </tr>
  </thead>

  <tbody>
    <% @drivers.each do |driver| %>
      <tr>
        <td><%= driver.full_name %></td>


        <td><%= driver.current_city %></td>
        <td><%= driver.desired_city %></td>
        <td><%= driver.desired_state %></td>
        <td><%= driver.desired_zip %></td>
        <td><%= driver.driver_id_tag %></td>
        <td><%= driver.driver_phone %></td>
        <td><%= driver.driver_truck_type %></td>
        <% if driver.active == true%>
        <td class="success"><%= humanize_boolean(driver.active?)%></td>
        <% else %>
        <td class="danger"><%= humanize_boolean(driver.active?) %></td>

        <%end %>
        <td><%= driver.driver_status %></td>
        <td><%= driver.driver_contract_number %></td>
        <td><%= driver.driver_availability %></td>
        <td><%= driver.driver_company %></td>
        <td><%= driver.comments %></td>

      </tr>
    <% end %>
  </tbody>
</table>