config/routes.rb
Rails.application.routes.draw do

  devise_for :users, skip: :registrations, controllers: {
    registrations: 'users/registrations'
  }

  as :user do
    get '/users' => 'users/registrations#index'
    get '/users/sign_up' => 'users/registrations#new', as: :new_user_registration
    get '/users/edit' => 'users/registrations#edit', as: :edit_user_registration
    post '/users' => 'users/registrations#create', as: :user_registration
    put '/users/edit/:id' => 'users/registrations#update', as: :update_user_registration
    patch '/users/:id' => 'users/registrations#update', as: :patch_user_registration
    delete '/users/:id' => 'users/registrations#destroy', as: :destroy_user_registration

    put '/users/password/:id' => 'users/registrations#update_password', as: :password
  end

  get 'drivers/reports' => 'drivers#reports'
  post 'drivers/state' => 'drivers#state_drivers', as: :state_drivers
  get 'drivers/state' => 'drivers#show_state_drivers', as: :show_state_drivers

  get 'reports/index' => 'reports#index'

  root 'drivers#index'
  resources :drivers

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Optruckboard</title>
  <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDT09gnN8Lxk1rZXaneZnvD1-fHaH0fVo4" type="text/javascript"></script>
  <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
</head>
<body>

  <% if user_signed_in? %>


    <% account_type = current_user.account_type %>

    <meta name="account-type" content=<%=account_type%>>

    <header class="navbar navbar-bg-faded">
       <%= link_to image_tag("logo.png", alt: "logo"), 'https://oncoreinc.com/?page_id=17055', target: :_blank, class: 'navbar-brand' %>
      <div class="container">
        <nav>
          <ul class="nav navbar-nav navbar-left">
            <li> <%=  link_to "Welcome, #{current_user.full_name}", drivers_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li> <%=  link_to "Home", drivers_path %></li>
            <li><%= link_to "Reports", drivers_reports_path %></li>
            <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
            <% if account_type == 'admin' %>
              <li><%= link_to "Manage Users", users_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

  <% end %>

  <% flash.each do |name, msg| %>
    <%= content_tag(:div, msg, id: "notice", class: "alert alert-#{name}") %>
  <% end %>

<%= yield %>

</body>
</html>